### PR TITLE
Adding (opt-in) for thin date with shorter container

### PR DESCRIPTION
**Pull request by ta1188**
This is an _opt-in_ feature by using the `showThinDate` property.

### CODE REVIEW

**Comment by rosemariesadler** [comment]
A couple thoughts on the functionality - the observer is only fired on changes to isDate, not to showThinDate, so if I set it to a date type field and then change it to display the thin dates, it won't work. Second thing I noticed is that it doesn't apply to the select menu dates.

**Comment by ta1188** [comment]
Issues should now be addressed. Let me know if you see anything missing.

**Comment by rosemariesadler** [comment]
Just wanted to make sure a couple of these changes were on purpose:
screen shot 2018-09-21 at 1 28 54 pm
screen shot 2018-09-21 at 1 29 03 pm
screen shot 2018-09-21 at 1 29 12 pm
screen shot 2018-09-21 at 1 29 19 pm

The bolding went away always in the dropdown from the input box, and from the select menu the bold got added to the selected item. This is without show-thin-date.

I'm not sure exactly what thin-date is supposed to change. The only change I'm seeing is from the select menu the bold gets turned off and the height of the items is shorter - is that what it's supposed to change?

**Comment by ta1188** [comment]
Hey Rose, I'm curious your set up for the last screenshot. On prod, our `standardized event date` drop-down shows

screen shot 2018-10-31 at 2 35 30 pm

**Pull request merged**
