### PR TITLE
[TW-3235] Resolves issue with non-translated link titles

### PR DESCRIPTION
**Pull request by drewswaycool**
See: https://fhjira.churchofjesuschrist.org/browse/TW-3235

This solution provides minimal impact on other languages. They will remain as they are until translations come back.

### CODE REVIEW

**Comment by rosemariesadler** [comment]
This seems like its going in the right direction.

**Comment by drewswaycool** [comment]
I actually have a way better solution now... implementing it currently.

**Comment by drewswaycool** [comment]
@rosemariesadler,

Question: Do we want to just have them retranslate and update strings? Or do we want to surgically pull out the correct text and move it to new keys in the other languages (seems like a lot of work, but it wouldn't have to be retranslated that way)?

**Review by rosemariesadler — COMMENTED** [review]
Yeah, we probably are good to submit again for translations since the key name for the main key didn't change, as long as it still displays properly. Have you tested it in other languages? If it works as it does currently in prod, then we're good to just merge and submit translations.

**Comment by drewswaycool** [comment]
@rosemariesadler yup - tested we're good to go!

**Review by rosemariesadler — APPROVED** [review]

**Pull request merged**
